import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

import { QRCodeGen } from '../src/ui/qr-code.js';
import { decodeQR } from '../src/vendor/qr-decode.js';
import { buildWhatsAppUrl, buildEmailUrl } from '../src/ui/share-actions.js';
import { createShareSectionHTML } from '../src/features/fundraisers/share.js';
import { SITE_SHARE_URL, toggleSiteSharePanel } from '../src/ui/site-share.js';
import { createFundraiserCard } from '../src/features/fundraisers/card.js';
import { openContextModal } from '../src/ui/context-modal.js';

const contentData = JSON.parse(readFileSync(new URL('../data/content.json', import.meta.url), 'utf8'));
const fundraisersData = JSON.parse(readFileSync(new URL('../data/fundraisers.json', import.meta.url), 'utf8'));

/**
 * Rasterizes an SVG string generated by QRCodeGen into RGBA pixel data at target display size (e.g., 220x220).
 * @param {string} svgStr
 * @param {number} targetSize
 * @returns {{ data: Uint8Array, width: number, height: number }}
 */
function rasterizeSvgToRgba(svgStr, targetWidth, targetHeight) {
  const widthAttr = svgStr.match(/width=\"(\d+)\"/);
  const heightAttr = svgStr.match(/height=\"(\d+)\"/);
  const renderWidth = targetWidth || (widthAttr ? parseInt(widthAttr[1]) : 220);
  const renderHeight = targetHeight || (heightAttr ? parseInt(heightAttr[1]) : 220);

  const viewBoxMatch = svgStr.match(/viewBox=\"0 0 (\d+) (\d+)\"/);
  if (!viewBoxMatch) throw new Error('viewBox attribute missing from SVG string');
  const viewSize = parseInt(viewBoxMatch[1]);
  const scale = renderWidth / viewSize;

  const data = new Uint8Array(renderWidth * renderHeight * 4);
  data.fill(255); // White background

  const dMatch = svgStr.match(/d=\"([^\"]+)\"/);
  if (!dMatch) throw new Error('d attribute missing from SVG path');
  const d = dMatch[1];

  let subpathStart = { x: 0, y: 0 };
  const matrix = Array.from({ length: viewSize }, () => new Array(viewSize).fill(false));

  const regex = /([MmLlHhVvZz])|(-?\d+(?:\.\d+)?)/g;
  let match;
  const tokens = [];
  while ((match = regex.exec(d)) !== null) {
    tokens.push(match[0]);
  }

  let i = 0;
  while (i < tokens.length) {
    const cmd = tokens[i++];
    if (cmd === 'M') {
      const x = parseFloat(tokens[i++]);
      const y = parseFloat(tokens[i++]);
      subpathStart = { x, y };
      matrix[Math.floor(y)][Math.floor(x)] = true;
    } else if (cmd === 'm') {
      const dx = parseFloat(tokens[i++]);
      const dy = parseFloat(tokens[i++]);
      const x = subpathStart.x + dx;
      const y = subpathStart.y + dy;
      subpathStart = { x, y };
      matrix[Math.floor(y)][Math.floor(x)] = true;
    } else if (cmd === 'h' || cmd === 'v' || cmd === 'H' || cmd === 'V') {
      i++;
    }
  }

  for (let my = 0; my < viewSize; my++) {
    for (let mx = 0; mx < viewSize; mx++) {
      if (matrix[my][mx]) {
        const startX = Math.round(mx * scale);
        const endX = Math.round((mx + 1) * scale);
        const startY = Math.round(my * scale);
        const endY = Math.round((my + 1) * scale);

        for (let py = startY; py < endY; py++) {
          for (let px = startX; px < endX; px++) {
            if (px >= 0 && px < renderWidth && py >= 0 && py < renderHeight) {
              const idx = (py * renderWidth + px) * 4;
              data[idx] = 0;
              data[idx + 1] = 0;
              data[idx + 2] = 0;
              data[idx + 3] = 255;
            }
          }
        }
      }
    }
  }

  return { data, width: renderWidth, height: renderHeight };
}

function parseSvgPathToMatrix(svgStr) {
  const viewBoxMatch = svgStr.match(/viewBox=\"0 0 (\d+) (\d+)\"/);
  if (!viewBoxMatch) throw new Error('viewBox missing');
  const viewSize = parseInt(viewBoxMatch[1]);
  const matrix = Array.from({ length: viewSize }, () => new Array(viewSize).fill(false));

  const dMatch = svgStr.match(/d=\"([^\"]+)\"/);
  if (!dMatch) throw new Error('d missing');
  const d = dMatch[1];

  let subpathStart = { x: 0, y: 0 };
  const regex = /([MmLlHhVvZz])|(-?\d+(?:\.\d+)?)/g;
  let match;
  const tokens = [];
  while ((match = regex.exec(d)) !== null) {
    tokens.push(match[0]);
  }

  let i = 0;
  while (i < tokens.length) {
    const cmd = tokens[i++];
    if (cmd === 'M') {
      const x = parseFloat(tokens[i++]);
      const y = parseFloat(tokens[i++]);
      subpathStart = { x, y };
      matrix[Math.floor(y)][Math.floor(x)] = true;
    } else if (cmd === 'm') {
      const dx = parseFloat(tokens[i++]);
      const dy = parseFloat(tokens[i++]);
      const x = subpathStart.x + dx;
      const y = subpathStart.y + dy;
      subpathStart = { x, y };
      matrix[Math.floor(y)][Math.floor(x)] = true;
    } else if (cmd === 'h' || cmd === 'v' || cmd === 'H' || cmd === 'V') {
      i++;
    }
  }

  return { matrix, viewSize };
}

test('QR Code Generation and Real Decode Verification for Donate URLs', () => {
  const testUrls = [
    'https://japiohopman.github.io/fundraiser',
    ...fundraisersData.fundraisers.map(f => f.donateUrl)
  ];

  for (const url of testUrls) {
    assert.ok(url.startsWith('https://whydonate.com/nl/donate/') || url === SITE_SHARE_URL, `QR test URL must be a /donate/ URL or site-wide share URL: ${url}`);
    assert.ok(!url.includes('/fundraising/'), `QR URL must not contain /fundraising/: ${url}`);
    assert.ok(!url.includes('#fundraiser-'), `QR URL must not contain internal anchor: ${url}`);

    const svg = QRCodeGen.createSVG(url);
    assert.ok(svg.includes('<svg'), `SVG output missing <svg tag for ${url}`);
    assert.ok(svg.includes('width="220"'), `SVG output must explicitly declare width="220" for production contract`);
    assert.ok(svg.includes('height="220"'), `SVG output must explicitly declare height="220" for production contract`);
    assert.ok(svg.includes('path'), `SVG output missing path element for ${url}`);

    // Parse production dimensions from SVG tag itself
    const widthMatch = svg.match(/width=\"(\d+)\"/);
    const heightMatch = svg.match(/height=\"(\d+)\"/);
    const prodWidth = parseInt(widthMatch[1]);
    const prodHeight = parseInt(heightMatch[1]);

    assert.equal(prodWidth, 220, 'Production width contract must equal 220');
    assert.equal(prodHeight, 220, 'Production height contract must equal 220');

    const rasterizedImage = rasterizeSvgToRgba(svg, prodWidth, prodHeight);
    const decodedUrl = decodeQR(rasterizedImage);

    assert.equal(decodedUrl, url, `Decoded QR text '${decodedUrl}' does not match original URL '${url}'`);
  }
});

test('Independent QR Finder Pattern Structural Correctness Check', () => {
  const testUrls = [
    'https://japiohopman.github.io/fundraiser',
    'https://japiohopman.github.io/fundraiser#fundraiser-manon-kinkt-shirts'
  ];

  for (const url of testUrls) {
    const svg = QRCodeGen.createSVG(url);
    const { matrix, viewSize } = parseSvgPathToMatrix(svg);

    // Verify 7x7 outer finder pattern structure independently of decoder
    const assertFinder = (startR, startC) => {
      for (let r = 0; r < 7; r++) {
        for (let c = 0; c < 7; c++) {
          const isOuter = (r === 0 || r === 6 || c === 0 || c === 6);
          const isInner = (r >= 2 && r <= 4 && c >= 2 && c <= 4);
          const expected = isOuter || isInner;
          const actual = matrix[startR + r][startC + c];
          assert.equal(actual, expected, `Finder module at (${startR + r}, ${startC + c}) must be ${expected}`);
        }
      }
    };

    // Finder patterns are at quietZone offset (2 modules in paulmillr/qr)
    const quietZone = 2;
    assertFinder(quietZone, quietZone); // Top-Left
    assertFinder(quietZone, viewSize - quietZone - 7); // Top-Right
    assertFinder(viewSize - quietZone - 7, quietZone); // Bottom-Left
  }
});

test('Fixed site-wide share panel contains direct site QR + Copy Link without WhatsApp or Email buttons', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');

  // Verify site share panel direct elements
  assert.ok(html.includes('id="site-share-panel"'), 'index.html must contain #site-share-panel');
  assert.ok(html.includes('id="site-qr-code-svg-container"'), '#site-share-panel must contain #site-qr-code-svg-container for direct QR display');
  assert.ok(html.includes('id="site-share-url-text"'), '#site-share-panel must contain #site-share-url-text for visible site URL');
  assert.ok(html.includes('id="site-copy-link-btn"'), '#site-share-panel must contain #site-copy-link-btn');

  // Verify WhatsApp and Email buttons are removed from fixed site share panel
  assert.ok(!html.includes('id="site-wa-share-btn"'), 'WhatsApp button must be removed from fixed site-share panel');
  assert.ok(!html.includes('id="site-email-share-btn"'), 'Email button must be removed from fixed site-share panel');
  assert.ok(!html.includes('id="site-native-share-btn"'), 'Native share button must be removed from fixed site-share panel');
  assert.ok(!html.includes('id="site-qr-code-btn"'), 'Separate QR button must be removed from fixed site-share panel as QR is rendered directly');

  // Verify Fundraiser card share section HTML has NO whatsapp or email buttons, but HAS copy link and qr code buttons
  for (const item of fundraisersData.fundraisers) {
    for (const lang of ['nl', 'en']) {
      const shareUrl = `${SITE_SHARE_URL}#fundraiser-${item.id}`;
      const titleText = item.title[lang] || item.title.nl;
      const purposeText = item.purpose[lang] || item.purpose.nl;

      const cardShareHtml = createShareSectionHTML(contentData.share, lang, shareUrl, titleText, purposeText, item.id);

      assert.ok(!cardShareHtml.includes('whatsapp-btn'), `WhatsApp button must NOT be present in card share HTML for ${item.id}`);
      assert.ok(!cardShareHtml.includes('email-btn'), `Email button must NOT be present in card share HTML for ${item.id}`);
      assert.ok(cardShareHtml.includes('copy-link-btn'), `Copy Link button must be present in card share HTML for ${item.id}`);
      assert.ok(cardShareHtml.includes('qr-code-btn'), `QR Code button must be present in card share HTML for ${item.id}`);
      assert.ok(cardShareHtml.includes('share-toggle-btn'), `Main Share toggle button must be present in card share HTML for ${item.id}`);
    }
  }
});

test('Site share and campaign QR content strings and destination context in content.json', () => {
  assert.ok(contentData.share.siteShareTitle.nl, 'Deel deze website');
  assert.ok(contentData.share.siteShareTitle.en, 'Share this website');

  assert.ok(contentData.share.siteShareDesc.nl.includes('transparantiesite'), 'siteShareDesc in NL must mention transparantiesite');
  assert.ok(contentData.share.siteShareDesc.en.includes('transparency site'), 'siteShareDesc in EN must mention transparency site');

  assert.equal(contentData.share.qrModalTitle.nl, 'QR-code voor donatiepagina');
  assert.equal(contentData.share.qrModalTitle.en, 'QR Code for donation page');

  assert.ok(contentData.share.qrModalDesc.nl.includes('WhyDonate-donatiepagina'), 'qrModalDesc in NL must explicitly identify WhyDonate-donatiepagina');
  assert.ok(contentData.share.qrModalDesc.en.includes('WhyDonate donation page'), 'qrModalDesc in EN must explicitly identify WhyDonate donation page');
});

test('Clipboard Share URL and Feedback Strings (NL and EN)', () => {
  // Site-wide share clipboard text
  assert.equal(SITE_SHARE_URL, 'https://japiohopman.github.io/fundraiser');
  assert.equal(contentData.share.linkCopied.nl, 'Link gekopieerd!');
  assert.equal(contentData.share.linkCopied.en, 'Link copied!');

  // Card clipboard share URLs
  for (const item of fundraisersData.fundraisers) {
    const cardUrl = `${SITE_SHARE_URL}#fundraiser-${item.id}`;
    assert.ok(cardUrl.endsWith(`#fundraiser-${item.id}`), `Card share URL must preserve anchor for ${item.id}`);
  }
});

test('Contract: Every fundraiser has required donateUrl corresponding to url', () => {
  for (const item of fundraisersData.fundraisers) {
    assert.strictEqual(
      typeof item.donateUrl,
      'string',
      `Fundraiser ${item.id} must have a required string donateUrl property`
    );
    assert.ok(
      item.url.includes('/nl/fundraising/'),
      `Fundraiser ${item.id} url must be a /nl/fundraising/ source URL (got: ${item.url})`
    );
    assert.ok(
      item.donateUrl.includes('/nl/donate/'),
      `Fundraiser ${item.id} donateUrl must be a /nl/donate/ destination URL (got: ${item.donateUrl})`
    );
    assert.strictEqual(
      item.donateUrl,
      item.url.replace('/fundraising/', '/donate/'),
      `Fundraiser ${item.id} donateUrl must correspond to url by replacing /fundraising/ with /donate/`
    );
  }

  // Explicit contract check for Jaap Hopman
  const jaapItem = fundraisersData.fundraisers.find(f => f.id === 'rooie-jaap-knives');
  assert.ok(jaapItem, 'Jaap Hopman fundraiser entry must exist');
  assert.strictEqual(
    jaapItem.donateUrl,
    'https://whydonate.com/nl/donate/koksmessen-voor-rooie-jaap',
    'Jaap Hopman donateUrl must equal exact expected URL'
  );
});

test('Compact Donate CTA rendering and accessibility in fundraiser cards uses /nl/donate/ destination (NL and EN)', () => {
  if (typeof globalThis.window === 'undefined') {
    globalThis.window = { location: { href: SITE_SHARE_URL } };
  }
  if (typeof globalThis.document === 'undefined') {
    globalThis.document = {
      createElement: () => ({
        className: '',
        id: '',
        innerHTML: '',
        querySelector: () => null,
        querySelectorAll: () => []
      })
    };
  }

  for (const item of fundraisersData.fundraisers) {
    const donateUrl = item.donateUrl;
    assert.ok(item.url.includes('/nl/fundraising/'), `Source URL must be /nl/fundraising/ for ${item.id}`);
    assert.ok(donateUrl.includes('/nl/donate/'), `Donate URL must be /nl/donate/ for ${item.id}`);

    if (item.id === 'rooie-jaap-knives') {
      assert.equal(donateUrl, 'https://whydonate.com/nl/donate/koksmessen-voor-rooie-jaap');
    }

    for (const lang of ['nl', 'en']) {
      const card = createFundraiserCard(item, contentData.fundraisersSection.labels, contentData.share, lang, contentData, {});
      const innerHTML = card.innerHTML;

      // Match donate-btn anchor link
      const donateMatch = innerHTML.match(/<a\s+[^>]*class=\"[^\"]*donate-btn[^\"]*\"[^>]*>([\s\S]*?)<\/a>/i) ||
                          innerHTML.match(/<a\s+href=\"[^\"]*\"[^>]*class=\"[^\"]*donate-btn[^\"]*\"[^>]*>([\s\S]*?)<\/a>/i);

      assert.ok(donateMatch, `Donate button anchor missing for ${item.id} (${lang})`);

      const fullAnchorTag = donateMatch[0];

      assert.ok(fullAnchorTag.includes(`href="${item.donateUrl}"`), `Donate URL must equal item.donateUrl (${item.donateUrl}) for ${item.id}`);

      // Extract visible text inside <span>
      const spanMatch = fullAnchorTag.match(/<span>([^<]+)<\/span>/i);
      assert.ok(spanMatch, `Visible text span missing in donate button for ${item.id}`);
      const visibleText = spanMatch[1].trim();

      assert.ok(visibleText.length > 0, `Visible Donate text must not be empty for ${item.id}`);

      // Extract aria-label attribute
      const ariaMatch = fullAnchorTag.match(/aria-label=\"([^\"]+)\"/i);
      assert.ok(ariaMatch, `aria-label missing on donate button for ${item.id} (${lang})`);
      const ariaLabel = ariaMatch[1];

      assert.ok(ariaLabel.includes(visibleText), `aria-label '${ariaLabel}' must contain identity name '${visibleText}' for ${item.id}`);

      const expectedPrefix = lang === 'en' ? 'Donate to' : 'Doneer aan';
      assert.ok(ariaLabel.startsWith(expectedPrefix), `aria-label '${ariaLabel}' must start with '${expectedPrefix}' for ${item.id} (${lang})`);
    }
  }
});

test('Context Modal renders generic Donate button using donateUrl with localized labels', () => {
  const bodyEl = { innerHTML: '' };
  const modalEl = {
    classList: { add: () => {} },
    removeAttribute: () => {}
  };
  const titleEl = { textContent: '' };

  const originalDoc = globalThis.document;
  globalThis.document = {
    getElementById: (id) => {
      if (id === 'context-modal') return modalEl;
      if (id === 'context-modal-title') return titleEl;
      if (id === 'context-modal-body') return bodyEl;
      return null;
    }
  };

  try {
    for (const item of fundraisersData.fundraisers) {
      const campaignContextData = contentData.fundraisersSection.campaignContext[item.id] || {};
      const state = {
        isContextModalOpen: false,
        contentData,
        fundraisersData
      };

      for (const lang of ['nl', 'en']) {
        openContextModal(state, campaignContextData, lang, null, item);

        const renderedHTML = bodyEl.innerHTML;
        assert.ok(renderedHTML.includes('context-modal-donate-btn'), `Context modal must contain context-modal-donate-btn for ${item.id} (${lang})`);
        assert.ok(renderedHTML.includes(`href="${item.donateUrl}"`), `Context modal Donate button must use item.donateUrl (${item.donateUrl}) for ${item.id} (${lang})`);

        const expectedLabel = lang === 'en' ? 'Donate on WhyDonate' : 'Doneer op WhyDonate';
        assert.ok(renderedHTML.includes(`<span>${expectedLabel}</span>`), `Context modal Donate button label must be '${expectedLabel}' for ${item.id} (${lang})`);

        // Check that artist/source link remains separate where applicable (e.g., Jim Gijbels or Jaap Hopman)
        if (campaignContextData.link && campaignContextData.link.url) {
          assert.ok(renderedHTML.includes(`href="${campaignContextData.link.url}"`), `Context modal must preserve external context link ${campaignContextData.link.url} for ${item.id}`);
          assert.ok(renderedHTML.includes('context-modal-link'), `Context modal external link must use class context-modal-link for ${item.id}`);
        }
      }
    }
  } finally {
    globalThis.document = originalDoc;
  }
});

test('Share panel focus lifecycle: immediate close prevents focus leaking into hidden panel', async () => {
  let focusedElement = null;
  const toggleBtn = {
    id: 'site-share-btn',
    setAttribute: () => {},
    focus: () => { focusedElement = toggleBtn; }
  };
  const firstAction = {
    className: 'site-share-action-btn',
    focus: () => { focusedElement = firstAction; }
  };
  const panel = {
    id: 'site-share-panel',
    hidden: true,
    classList: { toggle: () => {} },
    querySelector: (selector) => selector === '.site-share-action-btn' ? firstAction : null
  };

  const originalDoc = globalThis.document;
  globalThis.document = {
    getElementById: (id) => {
      if (id === 'site-share-btn') return toggleBtn;
      if (id === 'site-share-panel') return panel;
      return null;
    },
    addEventListener: () => {},
    removeEventListener: () => {}
  };

  try {
    const state = { isSiteShareOpen: false };

    // 1. Open share panel
    toggleSiteSharePanel(state, true);
    assert.equal(state.isSiteShareOpen, true);
    assert.equal(panel.hidden, false);

    // 2. Immediately close share panel before timer fires
    toggleSiteSharePanel(state, false);
    assert.equal(state.isSiteShareOpen, false);
    assert.equal(panel.hidden, true);

    // 3. Wait for timer to elapse
    await new Promise((resolve) => setTimeout(resolve, 80));

    // 4. Verify focus did NOT move to firstAction in hidden panel
    assert.notEqual(focusedElement, firstAction, 'Focus must NOT leak to firstAction inside hidden panel after immediate close');
  } finally {
    globalThis.document = originalDoc;
  }
});

test('QR Modal HTML structure and accessibility attributes in index.html', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');

  assert.ok(html.includes('id="qr-modal"'), 'index.html must contain #qr-modal');
  assert.ok(html.includes('role="dialog"'), 'qr-modal must have role="dialog"');
  assert.ok(html.includes('aria-modal="true"'), 'qr-modal must have aria-modal="true"');
  assert.ok(html.includes('id="qr-modal-campaign-name"'), 'qr-modal must have #qr-modal-campaign-name element');
  assert.ok(html.includes('id="qr-code-svg-container"'), 'qr-modal must have #qr-code-svg-container element');
  assert.ok(html.includes('id="qr-modal-url-text"'), 'qr-modal must have #qr-modal-url-text element for visible URL');
  assert.ok(html.includes('id="qr-modal-close-btn"'), 'qr-modal must have #qr-modal-close-btn element');
});
